services:
  zookeeper:
    image: zookeeper:3.8
    # Always pull docker image
    #pull_policy: always
    restart: always
    hostname: zookeeper

    environment:
      - TZ=${TIMEZONE}
      - ZOO_HEAP_SIZE=2G
      - ZOO_STANDALONE_ENABLED=true

    ports:
      # ---- Format: ----
      # [HOST-ADDR : ] HOST-PORT : DOCKER-PORT
      - "${HOST_PORT_ZK}:2181"

    networks:
      - net

    volumes:
      # ---- Format: ----
      # HOST-DIRECTORY : DOCKER-DIRECTORY

      # Mount custom intranet
      - ${VOLUME_PATH}/zookeeper/data:/data:rw${MOUNT_OPTIONS}
      - ${VOLUME_PATH}/zookeeper/datalog:/datalog:rw${MOUNT_OPTIONS}

networks:
  net:
    name: ${COMPOSE_NETWORK_NAME}
    driver: bridge