services:
  activemq:
    image: apache/activemq-classic:latest
    # Always pull docker image
    #pull_policy: always
    restart: always
    hostname: activemq
    environment:
      - TZ=${TIMEZONE}
      - ACTIVEMQ_OPTS_MEMORY=${ACTIVEMQ_OPTS_MEMORY}
      - ACTIVEMQ_OPTS=${ACTIVEMQ_OPTS}
      - ACTIVEMQ_CONNECTION_USER=${ACTIVEMQ_CONNECTION_USER}
      - ACTIVEMQ_CONNECTION_PASSWORD=${ACTIVEMQ_CONNECTION_PASSWORD}
      - ACTIVEMQ_JMX_USER=${ACTIVEMQ_JMX_USER}
      - ACTIVEMQ_JMX_PASSWORD=${ACTIVEMQ_JMX_PASSWORD}
      - ACTIVEMQ_WEB_USER=${ACTIVEMQ_WEB_USER}
      - ACTIVEMQ_WEB_PASSWORD=${ACTIVEMQ_WEB_PASSWORD}
    ports:
      # ---- Format: ----
      # [HOST-ADDR : ] HOST-PORT : DOCKER-PORT
      - "${HOST_PORT_ACTIVEMQ}:61616"
      - "${HOST_PORT_ACTIVEMQ_MANAGEMENT}:8161"

    volumes:
      # ---- Format: ----
      # HOST-DIRECTORY : DOCKER-DIRECTORY
      - ${VOLUME_PATH}/activemq:/opt/apache-activemq/data:rw${MOUNT_OPTIONS}

    networks:
      - net

networks:
  net:
    name: ${COMPOSE_NETWORK_NAME}
    driver: bridge
