version: '3'
services:
  openresty:
    image: bypanel/openresty
    # Always pull docker image
    #pull_policy: always
    restart: always
    hostname: openresty

    environment:
      ##
      ## Debug/Logging
      ##
      - DEBUG_ENTRYPOINT=${DEBUG_ENTRYPOINT:-2}
      - DEBUG_RUNTIME=1
      - DOCKER_LOGS

      ##
      ## Adjust timezone
      ##
      - TIMEZONE

      ##
      ## UserID and GroupID
      ##
      - NEW_UID
      - NEW_GID

    ports:
      # ---- Format: ----
      # [HOST-ADDR : ] HOST-PORT : DOCKER-PORT
      - "${HOST_PORT_OPENRESTY}:80"
      - "${HOST_PORT_OPENRESTY_SSL}:443"

    networks:
      - bypanel-network

    volumes:
      # ---- Format: ----
      # HOST-DIRECTORY : DOCKER-DIRECTORY

      # Mount custom intranet
      - ${BASE_DATA_PATH}/webroot:/var/www:rw${MOUNT_OPTIONS}

      # Mount custom web server config directory
      - ${BYPANEL_PATH}/cfg/openresty:/etc/nginx:rw${MOUNT_OPTIONS}

      # Mount logs
      - ${BASE_DATA_PATH}/logs/openresty:/var/log/nginx:rw${MOUNT_OPTIONS}

networks:
  bypanel-network:
    driver: bridge
