version: '3'
services:
  mysql-cron-backup:
    image: fradelg/mysql-cron-backup
    # Always pull docker image
    #pull_policy: always
    restart: unless-stopped
    hostname: mysql-cron-backup
    depends_on:
      - mysql

    environment:
      - TZ=${TIMEZONE}
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASS=${MYSQL_ROOT_PASSWORD}
      - MAX_BACKUPS=15
      - INIT_BACKUP=0
      # Every day at 03:00
      - CRON_TIME=0 3 * * *
      # Make it small
      - GZIP_LEVEL=9
      # As of MySQL 8.0.21 this is needed
      - MYSQLDUMP_OPTS=--no-tablespaces

    networks:
      - net

    volumes:
      - ${VOLUME_PATH}/backups:/backup:rw${MOUNT_OPTIONS}

networks:
  net:
    driver: bridge
